name: Frontend Deployment

on:
  repository_dispatch:
    types: [deploy]
  push:
    branches:
        - main
  pull_request:
    branches:
        - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build Docker image for React app
      run: |
        # Build the Docker image
        docker build -t ${{ secrets.DOCKER_USERNAME }}/pas-frontend:latest .
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Set your Docker Hub username in GitHub secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Set your Docker Hub password in GitHub secrets

    - name: Push Docker image to Docker Hub
      run: |
        docker push abdulmkhan325/pas-frontend:latest
    

