name: Deploy WebPAS Frontend Using Helm

on:
  workflow_dispatch:
    inputs:
      hospital_name:
        description: 'Choose the hospital to deploy'
        required: true
        type: choice
        options:
          - cabrini
          - stvincent

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'

    - name: Configure Minikube
      run: |
        minikube start
        kubectl cluster-info

    - name: Create Namespace if not exists
      run: |
        kubectl create namespace ${{ github.event.inputs.hospital_name }} || echo "Namespace exists"

    - name: Deploy with Helm
      run: |
        helm upgrade --install webpas-frontend ./helm \
          --namespace ${{ github.event.inputs.hospital_name }} \
          --values ./helm/values-${{ github.event.inputs.hospital_name }}.yaml
