name: Deploy WebPAS Frontend Using Helm

on:
  workflow_dispatch:
    inputs:
      hospital_name:
        description: 'Choose the hospital to deploy'
        required: true
        type: choice
        options:
          - cabrini
          - stvincent

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'

    - name: Set up Minikube
      run: |
          # Check if Minikube is running
          if ! minikube status | grep -q "host: Running"; then
            echo "Minikube is not running, starting Minikube..."
            minikube start --driver=docker
          else
            echo "Minikube is already running."
          fi

    - name: Create Namespace if not exists
      run: |
        kubectl create namespace ${{ github.event.inputs.hospital_name }} || echo "Namespace exists"

    - name: Deploy with Helm
      run: |
        helm upgrade --install webpas-frontend ./k8s/helm \
          --namespace ${{ github.event.inputs.hospital_name }} \
          --values ./k8s/helm/values-${{ github.event.inputs.hospital_name }}.yaml
