name: Frontend Deployment for webPAS
on:
  workflow_dispatch:
    inputs:
      hospital_name:
        description: 'Choose the hospital to deploy'
        required: true
        type: choice
        options:
          - cabrini
          - stvincent
          
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
       
      - name: Deploy to Minikube
        run: |
          HOSPITAL=${{ github.event.inputs.hospital_name }}
          helm upgrade --install webpas-frontend ./helm/webpas-frontend-chart \
            -f helm/webpas-frontend-chart/values-$HOSPITAL.yaml \
            --namespace $HOSPITAL
