name: Frontend Deployment for webPAS
on:
  workflow_dispatch:
    inputs:
      hospital_name:
        description: 'Choose the hospital to deploy'
        required: true
        type: choice
        options:
          - cabrini
          - stvincent
          
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
       
      - name: Deploy with Helm
        run: |
          helm upgrade --install webpas-frontend ./helm \
            --namespace ${{ github.event.inputs.hospital_name }} \
            --values ./helm/values-${{ github.event.inputs.hospital_name }}.yaml
